create simple authorization with exposed db
hexagon-team/it-interview-backend pull request #1
Opened 2022-07-10 17:38 UTC by polygloto

2022-07-11 16:07 UTC, Yami-666 requested changes

2022-07-11 16:07 UTC, Yami-666 commented on src/main/kotlin/com/hexagonteam/utils/CommonUtils.kt
> +    // TODO Bro, replace it with real token 🤡
💩

2022-07-11 16:07 UTC, Yami-666 commented on src/main/kotlin/com/hexagonteam/constants/UrlConstants.kt
> + * example url - https://video.syncended.dev:25/videoplayer?id=123#00h15m30s
Давай сделаем отдельный файл для констант для каждой части url, чтобы все это не превратилось в свалку. А для конфигурации базы данных мы создадим отдельный файл, например, DatabaseConfigConstants

2022-07-11 16:07 UTC, Yami-666 commented on src/main/kotlin/com/hexagonteam/constants/UrlConstants.kt
> +    const val DATABASE_URL = "jdbc:postgresql://localhost:5432/it-interview"
Вынеси это в отдельный файлик, пожалуйста

2022-07-11 16:07 UTC, Yami-666 commented on src/main/kotlin/com/hexagonteam/database/tokens/Tokens.kt
> +    private val id = Tokens.varchar(name = "id", length = 50)
Как тебе идея унифицировать длину всех строк? Чтобы не вводить их каждый раз. Как, например, это сделано в sql, что можно выбрать короткий, длинный текст. Также сделать набор ext по типу: shortVarchar(name = "id")

2022-07-11 16:07 UTC, Yami-666 commented on src/main/kotlin/com/hexagonteam/database/users/Users.kt
> +        } catch (exception: Exception) {
Мне кажется, что от такого tryCatch не особо много пользы. А ещё он не поймает throwable

2022-07-11 16:07 UTC, Yami-666 commented on src/main/kotlin/com/hexagonteam/login/LoginRouting.kt
> +            if (user == null) {
Почему бы не сделать вот так:
```
if (user == null) {
    call.respond(HttpStatusCode.BadRequest, message = "User not found")
    return@post
}

if (user.password == receive.password) {
    val token = generateToken()
    val tokenDto = TokenDto(
        rowId = UUID.randomUUID().toString(), // TODO how to replace it with autogenerate field?
        login = receive.login,
        token = token
    )
    Tokens.insert(tokenDto)

    call.respond(LoginResponseRemote(token))

} else call.respond(HttpStatusCode.BadRequest, message = "Invalid password")
```

Я не знаю, код после вызова call.respond продолжает выполнение вниз? Или он прекращает выполнение post лямбды?

2022-07-11 16:07 UTC, Yami-666 commented on src/main/kotlin/com/hexagonteam/login/LoginRouting.kt
> +            if (user == null) {
Это позволит избежать вложенности

2022-07-11 16:07 UTC, Yami-666 commented on src/main/kotlin/com/hexagonteam/login/LoginRouting.kt
> +                        rowId = UUID.randomUUID().toString(), // TODO how to replace it with autogenerate field?
Не забудь оставить карточку на туду

2022-07-11 16:07 UTC, Yami-666 commented on src/main/kotlin/com/hexagonteam/plugins/Routing.kt
> -            call.respondText("Hello World!")
Ворлд больше не хеллоу? =(

2022-07-11 16:07 UTC, Yami-666 commented on src/main/kotlin/com/hexagonteam/registration/RegistrationRouting.kt
> +                call.respond(HttpStatusCode.Conflict, message = "User already exists")
Как думаешь, может быть стоит собрать в одном месте где-нибудь все возможные ошибки, чтобы каждый раз это не писать? Типо sealead класса какого-нибудь? Как задел на будущее, хотя можно оставить и так... 🤔

2022-07-11 16:13 UTC, Yami-666 commented on src/main/kotlin/com/hexagonteam/registration/RegistrationRouting.kt
> +            val receive = call.receive<RegistrationReceiveRemote>()
Давай раздробим эти if-else выражения на функции, чтобы было проще читать и не было большой вложенности? Например:
 `
if (predicate) { 
    func()
} else { 
    elseFunc()
 }
`

2022-07-11 16:16 UTC, syncended commented on src/main/kotlin/com/hexagonteam/constants/UrlConstants.kt
> + * example url - https://video.syncended.dev:25/videoplayer?id=123#00h15m30s
English please, ne umeyu v russkii

2022-07-11 16:22 UTC, syncended commented on src/main/kotlin/com/hexagonteam/constants/UrlConstants.kt
> +    const val DATABASE_URL = "jdbc:postgresql://localhost:5432/it-interview"
Предлагаю завести .properties файл, что бы не пересобирать сервак если что

2022-07-11 16:36 UTC, polygloto commented on src/main/kotlin/com/hexagonteam/login/LoginRouting.kt
> +            if (user == null) {
Он прекращает выполнение лямбды

2022-07-11 19:05 UTC, polygloto commented on src/main/kotlin/com/hexagonteam/database/tokens/Tokens.kt
> +    private val id = Tokens.varchar(name = "id", length = 50)
В sql, да и в других бд (в нашем случае postgre) ты задаешь все руками. Как видишь, таблицы у нас - это объекты, они уже и так несут в себе константные значения, которые я бы не стал выносить еще куда то. К тому же, зачастую, ты можешь заменить в бд длину поля и не хочешь, чтобы это аффектило как-то на другие таблицы, а так придется лезть и новые константы добавлять. 
![image](https://user-images.githubusercontent.com/55101363/178338691-733f286b-8e72-4234-bb6e-b111e895d46e.png)

Использовать обертки где не попадя я бы так же не хотел. Я считаю, что это просто лишний шит, который не несет никакой пользы. Я бы выносил в ext только то, что сильно упрощает чтение кода. Интересно услышать мнение @syncended

2022-07-11 19:11 UTC, Yami-666 commented on src/main/kotlin/com/hexagonteam/database/users/Users.kt
> +        } catch (exception: Exception) {
Лучше было бы пробросить это исключение выше, например, UserNotFoundException и обработать его соотв. ошибкой для клиента

2022-07-11 20:35 UTC, syncended requested changes

2022-07-11 20:35 UTC, syncended commented on gradle.properties
> +exposed_version=0.37.3
buildSrc?

2022-07-11 20:35 UTC, syncended commented on src/main/kotlin/com/hexagonteam/constants/UrlConstants.kt
> +    const val DATABASE_URL = "jdbc:postgresql://localhost:5432/it-interview"
@polygloto чекни Properties класс, он умеет все это читать и писать на лету

2022-07-11 20:35 UTC, syncended commented on src/main/kotlin/com/hexagonteam/constants/UrlConstants.kt
> +}
No newline at end of file

2022-07-11 20:35 UTC, syncended commented on src/main/kotlin/com/hexagonteam/database/tokens/Tokens.kt
> +    private val id = Tokens.varchar(name = "id", length = 50)
Смотря что мы хотим, не думаю что на текущих масштабах нам критично как-то сильно оптимизировать все это дело, потом, если что, подкрутим

2022-07-11 20:35 UTC, syncended commented on src/main/kotlin/com/hexagonteam/database/users/Users.kt
> +                val user = Users.select { Users.login.eq(login) }.single()
exposed вроде умеет в опциональный результат

2022-07-11 20:35 UTC, syncended commented on src/main/kotlin/com/hexagonteam/database/users/Users.kt
> +        } catch (exception: Exception) {
мой вариант выше

2022-07-11 20:35 UTC, syncended commented on src/main/kotlin/com/hexagonteam/login/LoginRemote.kt
> +    val login: String,
SerialNames? или не будем на серваке с этим мозг себе любить?

2022-07-11 20:35 UTC, syncended commented on src/main/kotlin/com/hexagonteam/login/LoginRouting.kt
> +fun Application.configureLoginRouting() {
Koin?
Мне кажется можно накрутить а-ля 
interface Router {
   fun route(app: Application)
}
а в main функции взять koin.getAll<Router>.forEach { it.route(this) }

2022-07-11 20:35 UTC, syncended commented on src/main/kotlin/com/hexagonteam/login/LoginRouting.kt
> +                if (user.password == receive.password) {
вложенные if'ы - зло)
давай как-то так
```kotlin
when {
   user == null -> ...
   user.password == receive.password -> ...
   else -> ...
}
```

2022-07-11 20:35 UTC, syncended commented on src/main/kotlin/com/hexagonteam/plugins/Routing.kt
> -            call.respondText("Hello World!")
Delete?

2022-07-11 20:35 UTC, syncended commented on src/main/kotlin/com/hexagonteam/registration/RegistrationRouting.kt
> +fun Application.configureRegistrationRouting() {
Koin? (предыдущий коммент)

2022-07-11 20:35 UTC, syncended commented on src/main/kotlin/com/hexagonteam/registration/RegistrationRouting.kt
> +    return email.isNotBlank() // TODO create validator
ticket

2022-07-24 07:02 UTC, polygloto commented on src/main/kotlin/com/hexagonteam/login/LoginRouting.kt
> +fun Application.configureLoginRouting() {
Пока не вижу смысла тащить koin. Исходя из документации и сэмплов других проектов - такой декларативный стиль применяется повсеместно

2022-07-24 07:12 UTC, polygloto commented on src/main/kotlin/com/hexagonteam/login/LoginRemote.kt
> +    val login: String,
Давай пока не будем. С экспоузом думаю тоже, если называет таблицы сразу одинаково, то появляется различный сахар

2022-07-31 18:46 UTC, syncended approved these changes

2022-07-31 18:46 UTC, syncended commented on src/main/kotlin/com/hexagonteam/database/users/Users.kt
> +    fun insert(userDto: UserDto): UserResult {
мб `Result<UserDto>`

2022-07-31 18:46 UTC, syncended commented on src/main/kotlin/com/hexagonteam/database/users/Users.kt
> +            transaction {
fun <T> safeTransaction(transaction: () -> T): Result<T> {
   return runCatching {
      transaction.invoke()
   }
}

2022-07-31 20:00 UTC, Yami-666 approved these changes

2022-08-01 09:05 UTC, merged